export const elements = {
  providerSelect: document.getElementById('voiceui-provider'),
  apiKeyInput: document.getElementById('voiceui-apikey'),
  apiKeyRow: document.getElementById('voiceui-apikey').closest('.voiceui-row'),
  apiKeyLinksRow: document.getElementById('voiceui-apikey-links-row'),
  dashscopeModelSelect: document.getElementById('voiceui-dashscope-model'),
  dashscopeModelRow: document.getElementById('voiceui-dashscope-model-row'),
  langSelect: document.getElementById('voiceui-lang'),
  micSelect: document.getElementById('voiceui-mic'),
  itnCheckbox: document.getElementById('voiceui-itn'),
  streamingCheckbox: document.getElementById('voiceui-streaming'),
  streamingRow: document.getElementById('voiceui-streaming-row'),
  autoCopyCheckbox: document.getElementById('voiceui-autocopy'),
  removePeriodCheckbox: document.getElementById('voiceui-remove-period'),
  ctxInput: document.getElementById('voiceui-ctx'),
  buttonModeSelect: document.getElementById('voiceui-button-mode'),
  scaleSelect: document.getElementById('voiceui-scale'),
  speedSlider: document.getElementById('voiceui-speed'),
  speedValue: document.getElementById('voiceui-speed-value'),
  hotkeyInput: document.getElementById('voiceui-hotkey'),
  cancelHotkeyInput: document.getElementById('voiceui-cancel-hotkey'),
  statusEl: document.getElementById('status'),
  versionEl: document.querySelector('.voiceui-version'),
  transcribeLink: document.getElementById('open-transcribe-page'),

  // Context modal elements
  ctxExpandBtn: document.getElementById('voiceui-ctx-expand'),
  ctxModal: document.getElementById('voiceui-ctx-modal'),
  ctxTextarea: document.getElementById('voiceui-ctx-textarea'),
  ctxSaveBtn: document.getElementById('voiceui-ctx-save'),
  ctxCancelBtn: document.getElementById('voiceui-ctx-cancel'),

  // OpenAI modal elements
  openaiProcessingCheckbox: document.getElementById('voiceui-openai-processing'),
  openaiConfigBtn: document.getElementById('voiceui-openai-config-btn'),
  openaiModal: document.getElementById('voiceui-openai-modal'),
  openaiBaseUrlInput: document.getElementById('voiceui-openai-baseurl'),
  openaiApiKeyInput: document.getElementById('voiceui-openai-apikey'),
  openaiModelIdInput: document.getElementById('voiceui-openai-modelid'),
  openaiSystemPromptTextarea: document.getElementById('voiceui-openai-systemprompt'),
  openaiSaveBtn: document.getElementById('voiceui-openai-save'),
  openaiCancelBtn: document.getElementById('voiceui-openai-cancel'),
  fetchModelsBtn: document.getElementById('voiceui-fetch-models-btn'),
  modelsDatalist: document.getElementById('voiceui-openai-models-list'),

  // Console modal elements
  consoleControlCheckbox: document.getElementById('voiceui-console-control'),
  consoleConfigBtn: document.getElementById('voiceui-console-config-btn'),
  consoleModal: document.getElementById('voiceui-console-modal'),
  consoleBaseUrlInput: document.getElementById('voiceui-console-baseurl'),
  consoleApiKeyInput: document.getElementById('voiceui-console-apikey'),
  consoleModelIdInput: document.getElementById('voiceui-console-modelid'),
  consoleSystemPromptTextarea: document.getElementById('voiceui-console-systemprompt'),
  consoleSaveBtn: document.getElementById('voiceui-console-save'),
  consoleCancelBtn: document.getElementById('voiceui-console-cancel'),
  fetchConsoleModelsBtn: document.getElementById('voiceui-fetch-console-models-btn'),
  consoleModelsDatalist: document.getElementById('voiceui-console-models-list'),
};
